# -*- coding: utf-8 -*-
"""My style-transfer-pytorch.ipynb

Automatically generated by Colaboratory.

# style-transfer-pytorch

An implementation of neural style transfer ([A Neural Algorithm of Artistic Style](https://arxiv.org/abs/1508.06576)) in PyTorch, supporting CPUs and Nvidia GPUs. It does automatic multi-scale (coarse-to-fine) stylization to produce high-quality high resolution stylizations, even up to print resolution if the GPUs have sufficient memory.

See [the GitHub repo](https://github.com/crowsonkb/style-transfer-pytorch) for more information.
"""

!nvidia-smi
# This next line is from the PyTorch website, for CUDA version 10.1 https://pytorch.org/get-started/locally/
!pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable.html
!git clone https://github.com/crowsonkb/style-transfer-pytorch
!pip install -e ./style-transfer-pytorch

# Art Styles

# Vision 1
!curl -OL 'https://www.dropbox.com/s/a5wvk53xo69ccce/V11Style.png'
!curl -OL 'https://www.dropbox.com/s/pgzgs1h0fr1v2th/V12Style.png'
!curl -OL 'https://www.dropbox.com/s/qj9l23f9dj6w8tw/V13Style.png'
!curl -OL 'https://www.dropbox.com/s/3gw87asac6ir2la/V14Style.png'

# Vision 2
!curl -OL 'https://www.dropbox.com/s/4m6dnwoz3rx9br9/V22Style.png'

# Vision 3
!curl -OL 'https://www.dropbox.com/s/g9jm0gmkq0mym6d/V31Style.png'
!curl -OL 'https://www.dropbox.com/s/1qqk1aclxpew77o/V32Style.png'
!curl -OL 'https://www.dropbox.com/s/xlvtdnd9uhn8x9o/V33Style.png'
!curl -OL 'https://www.dropbox.com/s/0r9hap99grlo3un/V34Style.png'

# Vision 4
!curl -OL 'https://www.dropbox.com/s/6s8xopgu3lo1ql7/V41Style.png'
!curl -OL 'https://www.dropbox.com/s/wy6shgy8wcrr937/V42Style.png'

# Monochrome Illutrations

# 1
!curl -OL 'https://www.dropbox.com/s/ivbf9hczpbgxjdg/V11.png'
!curl -OL 'https://www.dropbox.com/s/z5v9cp4lj8a1np6/V12Inverted.png'
!curl -OL 'https://www.dropbox.com/s/eu70097vfdk93oa/V13.png'
!curl -OL 'https://www.dropbox.com/s/otwbuiy6248moqw/V14.png'

# 2
# Only skeleton is needed, portal and tree will be from vision 1 and 3
!curl -OL 'https://www.dropbox.com/s/710gvhd1wn28z87/V22.png'

#3
!curl -OL 'https://www.dropbox.com/s/t5n38d739kwq930/V31.png'
!curl -OL 'https://www.dropbox.com/s/qt4q9kvc0zhjjqf/V32.png'
!curl -OL 'https://www.dropbox.com/s/vuk5z80yrrif3lj/V33.png'
!curl -OL 'https://www.dropbox.com/s/mfdw0s9m3kpnyuo/V34.png'

#4
# Only man and distillation machinery needed
!curl -OL 'https://www.dropbox.com/s/kcqasi0ikcm7x44/V41.png'
!curl -OL 'https://www.dropbox.com/s/u2e9e29ob8cckhx/V42.png'

#1
#!style_transfer V11.png V11Style.png -s 480 -o V11Out.png
#$!style_transfer V12Inverted.png V12Style.png -s 480 -o V12Out.png
#!style_transfer V13.png V13Style.png -s 480 -o V13Out.png
#!style_transfer V14.png V14Style.png -s 480 -o V14Out.png

#2
#!style_transfer V22.png V22Style.png -s 480 -o V22Out.png

#3
#!style_transfer V31.png V31Style.png -s 480 -o V31Out.png
!style_transfer V32.png V32Style.png -s 480 -o V32Out.png
!style_transfer V33.png V33Style.png -s 480 -o V33Out.png
#!style_transfer V34.png V34Style.png -s 480 -o V34Out.png

#4
!style_transfer V41.png V41Style.png -s 480 -o V41Out.png
#!style_transfer V42.png V42Style.png -s 480 -o V42Out.png

IPython.display.Image('V41Out.png')